# Generated by Django 5.1 on 2024-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_proxima_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='proxima_verificacao',
            field=models.DateTimeField(),
        ),
    ]
