# Generated by Django 5.1 on 2024-10-11 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipamento_proxima_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='proxima_verificacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
