# Generated by Django 5.1 on 2024-10-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_computador_sistema_operacional_and_more'),
        ('equipamentos', '0008_alter_computador_sistema_operacional_and_more'),
    ]

    operations = [
    ]
