# Generated by Django 5.1 on 2024-11-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_inspecaocomputador_dados_json'),
        ('equipamentos', '0009_merge_20241025_1013'),
    ]

    operations = [
    ]
