# Generated by Django 5.1 on 2024-10-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_ocorrenciacomputador_tipo_ocorrencia'),
        ('ocorrencias', '0002_remove_ocorrenciacomputador_operador_and_more'),
    ]

    operations = [
    ]
